#common
application_name = "DevOpsTesting"

#android config
package_name = "com.devopstesting"
gradle_file = "./android/app/build.gradle"

platform :android do
  #before_all do
    #setup_circle_ci
  #end

  desc "Increase Android Version By Options"
  lane :increase_version do |options|
    type = options[:type]
    command = "cd ../android && ./gradlew bumpVersion#{type}"
    sh(command)
  end

  desc "Build android"
  lane :build do |options|
    variant = options[:variant]
    command = "cd ../android && "

    if variant === "debug"
      command += "ENVFILE=.env.dev "
    elsif variant === "staging"
      command += "ENVFILE=.env.staging "
    elsif variant === "release"
      command += "ENVFILE=.env.release "
    end

    command += "./gradlew assemble#{variant}"
    sh(command)
  end
end